#!/usr/bin/env bash
# Configures a new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
newstring="rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4/ permanent;"
sudo sed -i "/server_name _/a $newstring" /etc/nginx/sites-available/default
sudo service nginx restart
