#!/usr/bin/env bash
# Configures a new Load Balancer

sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6
sudo apt-get install haproxy=1.6.\*
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
sed -i "$ a\frontend http_front\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend http_back" /etc/haproxy/haproxy.cfg
sed -i "$ a\backend http_back\n\tbalance roundrobin\n\tserver 2124-web-01 34.75.147.95:80 check\n\tserver 2124-web-02 104.196.199.220:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
