#!/usr/bin/env bash
# Configures a new Load Balancer

sudo apt-get update
sudo apt-get install -y haproxy=1.6.\*
sudo sed -i "$ a\frontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\backend http_back\n\tbalance roundrobin\n\tserver 2124-web-01 34.75.147.95:80 check\n\tserver 2124-web-02 104.196.199.220:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
