#!/usr/bin/env bash
# configures a server to listen to port 80
sudo sed -i "s/listen [::]:8080 default_server ipv6only=on/listen [::]:80 default_server ipv6only=on/" /etc/nginx/sites-available/default
sudo sed -i "s/listen [::]:8080 default_server ipv6only=on/listen [::]:80 default_server ipv6only=on/" /etc/nginx/sites-enable/default
sudo service nginx restart
